"""Unit tests for TemplateGenerator in wtinydb-mcp."""

from wtinydb_mcp.templates import TemplateGenerator


def test_template_folders_and_files():
    """Validates folder generation and starter file blueprint structure for scaffolding."""
    folders = TemplateGenerator.get_folders("standard")
    assert "models" in folders
    assert "repositories" in folders

    files = TemplateGenerator.get_files_blueprint("standard", "my_app")
    assert "main.py" in files
    assert "README.md" in files
    assert "models/user.py" in files
    assert "Generated by WTinyDB MCP by wisrovi" in files["README.md"]
