"""Unit tests for FastMCP tools in wtinydb-mcp server."""

from wtinydb_mcp.server import (
    deploy_wtinydb_scaffolding,
    generate_wtinydb_crud,
    get_wtinydb_architect_blueprints,
    get_wtinydb_architect_manual,
    search_wtinydb_pattern,
    validate_model_schema,
)


def test_validate_model_schema_tool():
    """Validates model schema validation tool with Pydantic code snippet."""
    valid_code = "from pydantic import BaseModel\nclass Customer(BaseModel):\n    name: str"
    res = validate_model_schema(valid_code)
    assert "Valid Model Validation Result" in res
    assert "Model looks good" in res

    invalid_code = "def foo(:"
    res_err = validate_model_schema(invalid_code)
    assert "Syntax Error" in res_err


def test_search_pattern_tool():
    """Validates search_wtinydb_pattern tool output format."""
    res = search_wtinydb_pattern("Pydantic")
    assert "wisrovi SUITE" in res
    assert "Pydantic Document Repository" in res


def test_blueprints_and_manual_tools():
    """Validates architectural blueprints and manual tools response strings."""
    blueprints = get_wtinydb_architect_blueprints()
    assert "WTINYDB EXPERT BLUEPRINTS" in blueprints

    manual = get_wtinydb_architect_manual()
    assert "WTINYDB ARCHITECT MANUAL" in manual
    assert "Generated by WTinyDB MCP by wisrovi" in manual


def test_generate_crud_tool():
    """Validates automatic CRUD repository code generation."""
    code_input = "from pydantic import BaseModel\nclass Note(BaseModel):\n    title: str"
    crud_output = generate_wtinydb_crud(code_input)
    assert "class NoteRepository:" in crud_output
    assert "def create(" in crud_output


def test_deploy_scaffolding_tool(tmp_path):
    """Validates deployment of project scaffolding to a target directory."""
    target_dir = str(tmp_path / "test_proj")
    res = deploy_wtinydb_scaffolding(target_dir, project_name="test_proj")
    assert "Success" in res
