"""WTinyDB Scaffolding Code and Folder Generator."""

from typing import Dict, List


class TemplateGenerator:
    """Generates standard directory structures and starter files for WTinyDB projects."""

    @staticmethod
    def get_folders(scaffold_type: str = "standard") -> List[str]:
        """Return list of directory relative paths to create."""
        return [
            "config",
            "models",
            "repositories",
            "services",
            "tests",
        ]

    @staticmethod
    def get_files_blueprint(scaffold_type: str = "standard", project_name: str = "wtinydb_project") -> Dict[str, str]:
        """Return dictionary of relative file paths and their starter contents."""
        settings_py = (
            "from dataclasses import dataclass\n"
            "import os\n\n"
            "@dataclass\n"
            "class DatabaseSettings:\n"
            "    db_path: str = os.getenv('TINYDB_PATH', 'app_data.json')\n"
            "    in_memory: bool = os.getenv('TINYDB_IN_MEMORY', 'False').lower() == 'true'\n"
        )

        user_model_py = (
            "from pydantic import BaseModel, Field\n"
            "from wtinydb import AuditMixin\n\n"
            "class User(AuditMixin, BaseModel):\n"
            "    name: str = Field(description='User name')\n"
            "    email: str = Field(description='User email')\n"
            "    role: str = Field(default='user', description='Role')\n"
        )

        user_repo_py = (
            "from wtinydb import WTinyDB, Q\n"
            "from config.settings import DatabaseSettings\n"
            "from models.user import User\n\n"
            "class UserRepository:\n"
            "    def __init__(self, settings: DatabaseSettings = None):\n"
            "        settings = settings or DatabaseSettings()\n"
            "        self.db = WTinyDB(User, db_path=settings.db_path, in_memory=settings.in_memory)\n\n"
            "    def create_user(self, user: User) -> User:\n"
            "        return self.db.insert(user)\n\n"
            "    def get_by_email(self, email: str):\n"
            "        return self.db.get_by_field('email', email)\n"
        )

        main_py = (
            f"'''{project_name} Entrypoint'''\n"
            "from models.user import User\n"
            "from repositories.user_repo import UserRepository\n\n"
            "def main():\n"
            "    repo = UserRepository()\n"
            "    user = repo.create_user(User(name='Alice', email='alice@example.com'))\n"
            "    print(f'User created: {user.name} (email: {user.email})')\n\n"
            "if __name__ == '__main__':\n"
            "    main()\n"
        )

        readme_md = (
            f"# {project_name}\n\n"
            "WTinyDB Document Store Application.\n\n"
            "## Architecture\n"
            "```mermaid\n"
            "flowchart TD\n"
            "    Main[main.py] --> Repo[UserRepository]\n"
            "    Repo --> WTinyDB[WTinyDB Engine]\n"
            "    WTinyDB --> JSON[(TinyDB JSON Storage)]\n"
            "```\n\n"
            "*Generated by WTinyDB MCP by wisrovi*\n"
        )

        return {
            "config/settings.py": settings_py,
            "models/user.py": user_model_py,
            "repositories/user_repo.py": user_repo_py,
            "main.py": main_py,
            "README.md": readme_md,
        }
